services:
  - type: web
    name: my-ecommerce-be
    env: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake assets:precompile && bundle exec rake db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-ecommerce-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
